EXTRA_CFLAGS += -Iarch/arm/mach-msm
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o

obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-input.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-misc.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-mmc.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-sound.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-panel.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-camera.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-pm.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-usb.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-connectivity.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += board-m4eu-nfc.o
obj-$(CONFIG_MACH_MSM7X25A_M4) += lge_gpio_h2w.o


obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_SUSPEND_AUTOTEST) += lge_suspend_autotest.o
