EXTRA_CFLAGS += -Iarch/arm/mach-msm
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o

obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-input.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-misc.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-sound.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-panel.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-camera.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-pm.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-usb.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-connectivity.o
obj-$(CONFIG_MACH_MSM7X27A_U0) += board-u0-nfc.o


obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_SUSPEND_AUTOTEST) += lge_suspend_autotest.o
