subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm

-include $(src)/Makefile.board

obj-$(CONFIG_MACH_LGE) += devices-lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o
obj-$(CONFIG_LGE_BOOT_MODE) += lge_boot_mode.o
#obj-$(CONFIG_LGE_SUSPEND_AUTOTEST) += lge_suspend_autotest.o
obj-$(CONFIG_LGE_BLOCKING_MONITOR) += lge_blocking_monitor.o
