#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> return current preset from $1. Special: return all presets if $1 is "ALL"
# Write -> set $2 preset in $1

SYSFS_FILE="$1"

# Knows presets, don't forget to add them to the case below
PRESETS="flat archi custom"
PRESET_FLAT="0 0 0 0 0"
PRESET_ARCHI="8 4 4 2 6"

if [[ "$SYSFS_FILE" = "ALL" ]]; then
	echo "$PRESETS"
else
	if [[ -z "$2" ]]; then # Read mode
		GAINS_CURRENT="$(tr -d '[:alpha:]' < "$SYSFS_FILE" | tr -d '[:punct:]')"
		case "$GAINS_CURRENT" in # Known presets case
			*"$PRESET_FLAT") echo "flat" ;; # Synapse return
			*"$PRESET_ARCHI") echo "archi" ;; # Synapse return
			*) echo "custom" ;; # Synapse return
		esac
	else # Write mode
		PRESET_CHOSEN="$(echo "$2" | tr '[:lower:]' '[:upper:]')" # To uppercase
		if [[ "$PRESET_CHOSEN" != "CUSTOM" ]]; then
			eval SYSFS_WRITE="\${PRESET_$PRESET_CHOSEN}" # eval is evil
			if [[ -n "$SYSFS_WRITE" ]]; then
				echo "$SYSFS_WRITE" > "$SYSFS_FILE" # Write effect
			fi
		fi
		echo "$2" # Synapse return
	fi
fi
