#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> return current value for given $1 step
# Write -> set $2 value for given $1 step

SYSFS_FILE="/sys/devices/system/cpu/cpu0/cpufreq/UV_uV_table"

if [[ -z "$2" ]]; then # Read mode
	sed -e 's/mhz://g;s/uV//g' < "$SYSFS_FILE" | while read UV_TABLE; do
		FREQ="$(echo "$UV_TABLE" | awk '{print $1}')"
		if [[ "$FREQ" -eq "$1" ]]; then
			echo "$UV_TABLE" | awk '{print $2}' # Synapse return
			break
		fi
	done
else # Write mode
	SYSFS_WRITE="$(
		sed -e 's/mhz://g;s/uV//g' < "$SYSFS_FILE" | (while read UV_TABLE; do
			FREQ="$(echo "$UV_TABLE" | awk '{print $1}')"
			if [[ "$FREQ" -eq "$1" ]]; then
				SYSFS_WRITE="$SYSFS_WRITE $2"
			else
				VALUE="$(echo "$UV_TABLE" | awk '{print $2}')"
				SYSFS_WRITE="$SYSFS_WRITE $VALUE"
			fi
		done
		echo "$SYSFS_WRITE")
	)"
	echo "$SYSFS_WRITE" > "$SYSFS_FILE" # Write effect
	echo "$2" # Synapse return
fi
