#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> return current value from $1 for given $2 channel
# Write -> set $3 value for given $2 channel in $1

SYSFS_FILE="$1"
CHANNEL="$2"

case "$CHANNEL" in
	L) CHANNEL="2" ;;
	R) CHANNEL="3" ;;
esac

if [[ -z "$3" ]]; then # Read mode
	awk "FNR == $CHANNEL {print \$NF}" < "$1" # Synapse return
else # Write mode
	if [[ "$CHANNEL" -eq 2 ]]; then # Left
		SYSFS_WRITE="$3 $(awk 'FNR == 3 {print $NF}' < "$1")"
	else # Right
		SYSFS_WRITE="$(awk 'FNR == 2 {print $NF}' < "$1") $3"
	fi
	echo "$SYSFS_WRITE" > "$SYSFS_FILE" # Write effect
	echo "$3" # Synapse return
fi
