EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7x27a_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7x27a-regulator_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7x27a-sound_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7627a-bt_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7627a-camera_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7627a-display_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7627a-io_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7627a-storage_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7627a-wlan_vee7.o
obj-$(CONFIG_MACH_MSM8X25_V7) += board-msm7x27a-usb_vee7.o
