EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7x27a_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7x27a-regulator_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7x27a-sound_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7627a-bt_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7627a-camera_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7627a-io_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7627a-storage_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7627a-wlan_vee3.o
obj-$(CONFIG_MACH_MSM7X25A_V3) += board-msm7627a-display_vee3.o
#obj-$(CONFIG_MACH_MSM7X25A_V3) += board-v3-panel.o
