EXTRA_CFLAGS += -Ilge/include
obj-$(CONFIG_LGE_FACTORY) += userDataBackUpDiag.o
obj-$(CONFIG_LGE_FACTORY) += lge_diag_eri.o
obj-$(CONFIG_LGE_FACTORY) += lg_diag_dload.o
obj-$(CONFIG_LGE_SUPPORT_RAPI) += LG_rapi_client.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_testmode.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_unifiedmsgtool.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_class.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_communication.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_event_log.o
obj-$(CONFIG_LGE_DIAGTEST) += lge_ats_input.o
obj-$(CONFIG_LGE_DIAG_KEYPRESS) += lg_diag_keypress.o
obj-$(CONFIG_LGE_EMMC_DIRECT_ACCESS) += lge_emmc_direct_access.o

