EXTRA_CFLAGS += -Ilge/include
obj-$(CONFIG_LGE_SUPPORT_RAPI) += LG_rapi_client.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_testmode.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_unifiedmsgtool.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_class.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_communication.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_event_log.o
obj-$(CONFIG_LGE_DIAG_KEYPRESS) += lg_diag_keypress.o
obj-$(CONFIG_LGE_DIAG_SCREENSHOT) += lg_diag_screen_shot.o
obj-$(CONFIG_LGE_DIAG_UDM) += lg_diag_udm.o
obj-$(CONFIG_LGE_DIAGTEST) += lge_ats_input.o
obj-$(CONFIG_LGE_EMMC_DIRECT_ACCESS) += lge_emmc_direct_access.o
obj-$(CONFIG_LGE_FACTORY) += userDataBackUpDiag.o
obj-$(CONFIG_LGE_FACTORY) += lge_diag_eri.o
obj-$(CONFIG_LGE_FACTORY) += lg_diag_dload.o

obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_helper.o

#[jinseok.choi@lge.com]2012-11-22 U0 emmc access via kernel [START]
obj-$(CONFIG_LGE_FW_HELPER) += lg_fw_helper_u0.o
#[jinseok.choi@lge.com]2012-11-22 U0 emmc access via kernel [END]

#obj-$(CONFIG_LGE_BOARD_SUPPORT) += devices_lge.o