# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
# LGE_UPDATE_S		20111129
# headset detect switch
obj-$(CONFIG_LGE_SWITCH_GPIO)	+= lge_gpio_switch.o
# LGE_UPDATE_E		20111129

