# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
# LGE_CHANGE_S, [hoseong.kang@lge.com] , 2012-03-12
# do not use, use arch/arm/mach-msm/lge/lge_gpio_h2w.c
# obj-$(CONFIG_LGE_SWITCH_GPIO)	+= lge_gpio_switch.o 
# LGE_CHANGE_E, [hoseong.kang@lge.com] , 2012-03-12

