# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
# LGE_UPDATE_S		20111129
# headset detect switch
ifeq ($(CONFIG_MACH_MSM7X27A_U0),y)
obj-$(CONFIG_LGE_SWITCH_GPIO)	+= lge_gpio_switch.o
endif
# LGE_UPDATE_E		20111129

