#
# Makefile for sensor drivers.
#
obj-$(CONFIG_SENSORS_BMM050)   += bmm050_driver.o bmm050.o
obj-$(CONFIG_FIH_GSENSOR_BMA250)	+= bma250.o
obj-$(CONFIG_SENSORS_CM36283)	+= cm36283.o
obj-$(CONFIG_STK_PS_INT_MODE)		+= stk_i2c_ps31xx_int.o
