#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_I2C) += synaptics_dsx_rmi4_i2c.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_DEV) += rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_FW_UPDATE) += rmi_fw_update.o

obj-y += FIH-touch-tool/
