#
# Makefile for nfc devices
#

/*LGE_CHANGE_S : seven.kim@lge.com kernel3.0 porting */
obj-$(CONFIG_LGE_NFC_NXP_PN544PN65N)	+= nfc_nxp_pn544pn65n.o
/*LGE_CHANGE_E : seven.kim@lge.com kernel3.0 porting */
obj-$(CONFIG_PN544_NFC)		+= pn544.o
