EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7x27a_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7x27a-regulator_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7x27a-sound_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7627a-bt_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7627a-camera_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7627a-io_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7627a-storage_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7627a-wlan_v1.o
obj-$(CONFIG_MACH_MSM7X25A_V1) += board-msm7627a-display_v1.o
